name: Compile LaTeX Doc

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: pi4-ers.tex

      - name: Upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: pi4-ers
          path: pi4-ers.pdf
